spring.application.name=payment
# Server
server.port=8081

# DATASOURCE (PostgreSQL)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/payment_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.hikari.schema=public

# JPA / Hibernate
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.producer.acks=all
spring.kafka.producer.retries=2147483647

spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5

spring.kafka.producer.properties.linger.ms=5
spring.kafka.producer.properties.batch.size=32768

spring.kafka.consumer.auto-offset-reset=earliest

# Info
info.app.name=AirBookingPetProject
info.app.version=1.0.0
info.app.description=Spring Boot pet project